import Head from "next/head";
import styles from "../styles/Home.module.css";
import Layout from "../components/Layout";
import Banner from "../components/Banner";

export default function Home() {
	const handleBannerOnClick = () => {
    console.log('hi banner button')
  };

	return (
		<Layout>
			<div className={styles.container}>
				<Head>
					<title>Local Coffees</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<main className={styles.main}>
					<Banner
						buttonText="View stores nearby"
						onClick={handleBannerOnClick}
					/>
				</main>
			</div>
		</Layout>
	);
}
